
debug = true

[enum]
remove_prefix = true
remove_unspecified_entry = true

[metadata.info]
description = "Just an API example"

[[metadata.servers]]
url = "http://dev.api.example.com"
description = "The development version of the API"

[[metadata.servers]]
url = "https://prod.api.example.com"
description = "The production version of the API"

[output]
path = "openapi"

[mikros]
use_outbound_messages = true
use_inbound_messages = true
settings_filename = "protoc-gen-mikros-extensions.toml"
keep_main_module_file_prefix = true
